# -*- mode: ruby -*-
# vi: set ft=ruby :






# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/xenial64"
  config.vm.synced_folder "/home/dbourasseau/project/girafe_deployment", "/home/ubuntu/girafedeployment"
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt-get install git curl -y

    git clone https://github.com/dngroup/girafedeployment.git
    curl -L https://bootstrap.saltstack.com -o install_salt.sh
    sudo sh install_salt.sh -P

  SHELL
end
